spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  sql:
    init:
      mode: always
logging:
  level:
    sql: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace